// <auto-generated />
namespace BookShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GetBookOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GetBookOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201806201412409_GetBookOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
